version: "3.9"
services:
   db:
    image: postgres:16.1
    restart: always
    #user: postgres
    # Open ports for testing
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: demo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -U user -d demo" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
